# You find the full pre-commit-tools docs here:
# https://pre-commit.com/

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.3
    hooks:
      # Run the Ruff formatter.
      - id: ruff-format
      # Run the Ruff linter.
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.28.0
    hooks:
      - id: django-upgrade
        args: [--target-version, "4.2"]
        stages: [ pre-push ]

  - repo: https://github.com/adamchainz/djade-pre-commit
    rev: 1.6.0
    hooks:
      - id: djade
        args: [ --target-version, "5.2" ]
        exclude: |
          (?x)^(
            charts/.*
            |.*\.py
          )$

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.9
    hooks:
      - id: djhtml
        # Indent only HTML files in template directories
        files: .*/?templates/.*\.html$
        stages: [ pre-push ]
        exclude: |
          (?x)^(
              .*/node_modules/.*|
          )$
      - id: djcss
        entry: djcss --tabwidth 2
        exclude: |
          (?x)^(
              .*/node_modules/.*|
          )$
        # Run this hook only on SCSS files (CSS and SCSS is the default)
        types: [ scss ]
        stages: [ pre-push ]
      - id: djjs
        # Exclude JavaScript files in vendor directories
        exclude: |
          (?x)^(
              .*/node_modules/.*|
          )$
        stages: [ pre-push ]

  - repo: https://github.com/ambient-innovation/boa-restrictor
    rev: v1.12.1
    hooks:
      - id: boa-restrictor
        args: [ --config=pyproject.toml ]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-illegal-windows-names
      - id: check-shebang-scripts-are-executable
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
