# Generated by Django 5.2.7 on 2025-11-02 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savegame', '0005_alter_savegame_coat_of_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_module', models.CharField(help_text="Python module path (e.g., 'apps.city.events.events.wandering_preacher')", max_length=255)),
                ('event_class_name', models.CharField(default='Event', help_text="Class name within the module (usually 'Event')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame')),
            ],
            options={
                'ordering': ['created_at'],
                'default_related_name': 'event_choices',
            },
        ),
    ]
