# Generated by Django 5.2.7 on 2025-11-01 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savegame', '0005_alter_savegame_coat_of_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Year when event occurred')),
                ('title', models.CharField(max_length=100, verbose_name='Event title')),
                ('message', models.TextField(verbose_name='Event message')),
                ('level', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('warning', 'Warning'), ('info', 'Info')], default='info', max_length=10, verbose_name='Message level')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Acknowledged')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame')),
            ],
            options={
                'ordering': ['created_at'],
                'default_related_name': 'event_notifications',
                'indexes': [models.Index(fields=['savegame', 'acknowledged'], name='event_event_savegam_fd3146_idx')],
            },
        ),
    ]
