# Generated by Django 5.0 on 2023-12-27 12:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEffect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=75, verbose_name="Name")),
                (
                    "attribute",
                    models.CharField(max_length=100, verbose_name="Attribute"),
                ),
                (
                    "min_amount",
                    models.PositiveSmallIntegerField(verbose_name="Min. Amount"),
                ),
                (
                    "max_amount",
                    models.PositiveSmallIntegerField(verbose_name="Max. Amount"),
                ),
                (
                    "sign",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Addition"), (2, "Subtraction")],
                        verbose_name="Sign",
                    ),
                ),
                (
                    "method",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Absolute"), (2, "Relative")],
                        verbose_name="Method",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Content type",
                    ),
                ),
            ],
            options={
                "default_related_name": "effects",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                ("text", models.TextField(verbose_name="Text")),
                (
                    "probability",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                        verbose_name="Probability",
                    ),
                ),
                (
                    "effect",
                    models.ManyToManyField(
                        to="event.eventeffect", verbose_name="Effect"
                    ),
                ),
            ],
            options={
                "default_related_name": "events",
            },
        ),
    ]
