# Generated by Django 5.0 on 2023-12-27 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEffectFilter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attribute",
                    models.CharField(max_length=75, verbose_name="Attribute"),
                ),
                (
                    "effect",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="event.eventeffect",
                        verbose_name="Event effect",
                    ),
                ),
            ],
            options={
                "default_related_name": "event_effect_filters",
            },
        ),
    ]
