# Generated by Django 5.2.7 on 2025-11-01 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventnotification',
            options={'default_related_name': 'event_notifications', 'ordering': ['year']},
        ),
        migrations.RemoveField(
            model_name='eventnotification',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eventnotification',
            name='level',
        ),
    ]
