# Generated by Django 5.0 on 2023-12-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0002_eventeffectfilter"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventeffectfilter",
            name="value",
            field=models.CharField(
                default="1", max_length=75, verbose_name="Attribute"
            ),
            preserve_default=False,
        ),
    ]
