# Generated by Django 5.0 on 2023-12-27 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_eventeffectfilter_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="probability",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Probability",
            ),
        ),
    ]
