# Generated by Django 5.0 on 2023-12-27 12:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_probability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="effect",
            new_name="effects",
        ),
    ]
