# Generated by Django 5.2.7 on 2025-10-29 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('savegame', '0005_alter_savegame_coat_of_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('condition_class', models.CharField(help_text="Python class path (e.g., 'apps.thread.conditions.prestige_defense.PrestigeDefenseThread')", max_length=200, verbose_name='Condition class')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Severity')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order', verbose_name='Order')),
            ],
            options={
                'ordering': ['order', 'name'],
                'default_related_name': 'thread_types',
            },
        ),
        migrations.CreateModel(
            name='ActiveThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at', models.PositiveSmallIntegerField(help_text='Year when thread became active', verbose_name='Activated at')),
                ('intensity', models.PositiveIntegerField(default=0, help_text='How severe the thread is (e.g., Prestige - Defense)', verbose_name='Intensity')),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame')),
                ('thread_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thread.threadtype')),
            ],
            options={
                'ordering': ['-intensity', 'thread_type__order'],
                'default_related_name': 'active_threads',
                'unique_together': {('savegame', 'thread_type')},
            },
        ),
    ]
