# Generated by Django 5.0 on 2024-05-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("city", "0032_buildingtype_is_unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="MilestoneLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone",
                    models.CharField(max_length=100, verbose_name="Milestone"),
                ),
                (
                    "accomplished_at",
                    models.PositiveSmallIntegerField(
                        help_text="Accomplished in this year",
                        verbose_name="Finished at",
                    ),
                ),
                (
                    "savegame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="city.savegame"
                    ),
                ),
            ],
            options={
                "default_related_name": "quest_logs",
            },
        ),
    ]
