# Generated by Django 5.2.3 on 2025-10-05 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0040_alter_savegame_coins"),
        ("milestone", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="milestonelog",
            options={"default_related_name": "milestone_logs"},
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="Name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Display order within the same level",
                        verbose_name="Order",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent milestone that must be completed before this one becomes available",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="milestone.milestone",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
                "default_related_name": "milestones",
            },
        ),
        migrations.AlterField(
            model_name="milestonelog",
            name="milestone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="milestone.milestone"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="milestonelog",
            unique_together={("savegame", "milestone")},
        ),
        migrations.CreateModel(
            name="MilestoneCondition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "condition_class",
                    models.CharField(
                        help_text="Python class path (e.g., 'apps.milestone.conditions.population.MinPopulationCondition')",
                        max_length=200,
                        verbose_name="Condition class",
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Value to pass to the condition class",
                        max_length=100,
                        verbose_name="Value",
                    ),
                ),
                (
                    "milestone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="milestone.milestone",
                    ),
                ),
            ],
            options={
                "default_related_name": "milestone_conditions",
            },
        ),
    ]
