# Generated by Django 5.2.3 on 2025-10-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestone', '0002_alter_milestonelog_options_milestone_and_more'),
        ('savegame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestonelog',
            name='savegame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame'),
        ),
    ]
