# Generated by Django 5.2.3 on 2025-10-19 18:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Savegame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('coins', models.SmallIntegerField(default=1000, verbose_name='Coins')),
                ('population', models.PositiveSmallIntegerField(default=0, verbose_name='Population')),
                ('unrest', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Unrest')),
                ('current_year', models.PositiveSmallIntegerField(default=1150, verbose_name='Current year')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('is_enclosed', models.BooleanField(default=False, verbose_name='Is enclosed by wall')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_related_name': 'savegames',
            },
        ),
    ]
