# Generated by Django 5.2.7 on 2025-10-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savegame', '0002_copy_savegame_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='savegame',
            name='coat_of_arms',
            field=models.ImageField(blank=True, null=True, upload_to='coat_of_arms/', verbose_name='Coat of Arms'),
        ),
    ]
