# Generated by Django 5.2.7 on 2026-03-15 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savegame', '0005_alter_savegame_coat_of_arms'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingSiege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attack_year', models.PositiveSmallIntegerField()),
                ('actual_strength', models.PositiveSmallIntegerField()),
                ('announced_strength', models.PositiveSmallIntegerField()),
                ('direction', models.CharField(choices=[('N', 'North'), ('S', 'South'), ('E', 'East'), ('W', 'West')], max_length=1)),
                ('resolved', models.BooleanField(default=False)),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame')),
            ],
            options={
                'default_related_name': 'pending_sieges',
            },
        ),
        migrations.CreateModel(
            name='SiegeChronicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('direction', models.CharField(max_length=1)),
                ('attacker_strength', models.PositiveSmallIntegerField()),
                ('defense_score', models.PositiveSmallIntegerField()),
                ('result', models.CharField(choices=[('repelled', 'Repelled'), ('damaged', 'Wall Damaged'), ('breached', 'Wall Breached')], max_length=10)),
                ('report_text', models.TextField()),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame')),
            ],
            options={
                'ordering': ['year'],
                'default_related_name': 'siege_chronicles',
            },
        ),
    ]
