# Generated by Django 5.2.7 on 2025-10-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0042_remove_savegame_map_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost_coins', models.SmallIntegerField(blank=True, null=True)),
                ('cost_population', models.SmallIntegerField(blank=True, null=True)),
                ('effect_unrest', models.SmallIntegerField(blank=True, null=True)),
                ('effect_coins', models.SmallIntegerField(blank=True, null=True)),
                ('effect_population', models.SmallIntegerField(blank=True, null=True)),
                ('cooldown_years', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EdictLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activated_at_year', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edict', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='edict.edict')),
                ('savegame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edict_logs', to='city.savegame')),
            ],
            options={
                'ordering': ['-activated_at_year'],
                'indexes': [models.Index(fields=['savegame', 'edict'], name='edict_edict_savegam_6d1975_idx')],
            },
        ),
    ]
