# Generated by Django 5.2.7 on 2025-10-19 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edict', '0001_initial'),
        ('milestone', '0002_alter_milestonelog_options_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edict',
            name='required_milestone',
            field=models.ForeignKey(blank=True, help_text='Milestone that must be completed before this edict becomes available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edicts', to='milestone.milestone'),
        ),
    ]
