# Generated by Django 5.2.3 on 2025-10-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edict', '0001_initial'),
        ('savegame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edictlog',
            name='savegame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edict_logs', to='savegame.savegame'),
        ),
    ]
