# Generated by Django 5.2.7 on 2025-10-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edict', '0003_edict_required_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='edict',
            name='cost_prestige',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='edict',
            name='required_prestige',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Minimum prestige required before this edict becomes available', null=True),
        ),
    ]
