# Generated by Django 5.2.7 on 2025-10-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edict', '0004_edict_cost_prestige_edict_required_prestige'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edict',
            name='cost_prestige',
        ),
    ]
