# Generated by Django 5.0 on 2023-12-13 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tile",
            unique_together={("savegame", "x", "y")},
        ),
    ]
