# Generated by Django 5.0 on 2023-12-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0002_alter_tile_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="building",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="city.building",
            ),
        ),
    ]
