# Generated by Django 5.0 on 2023-12-13 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0003_tile_building"),
    ]

    operations = [
        migrations.AddField(
            model_name="tile",
            name="tile_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="city.tiletype",
            ),
            preserve_default=False,
        ),
    ]
