# Generated by Django 5.0 on 2023-12-13 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0005_alter_building_options_alter_savegame_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiletype",
            name="probability",
            field=models.PositiveSmallIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Probability weight",
            ),
        ),
    ]
