# Generated by Django 5.0 on 2023-12-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0006_alter_tiletype_probability"),
    ]

    operations = [
        migrations.AddField(
            model_name="tiletype",
            name="map_color",
            field=models.CharField(default="red", max_length=10),
            preserve_default=False,
        ),
    ]
