# Generated by Django 5.0 on 2023-12-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0007_tiletype_map_color"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tiletype",
            name="map_color",
            field=models.CharField(max_length=20),
        ),
    ]
