# Generated by Django 5.0 on 2023-12-23 17:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0008_alter_tiletype_map_color"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tiletype",
            old_name="map_color",
            new_name="color_class",
        ),
    ]
