# Generated by Django 5.0 on 2023-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0009_rename_map_color_tiletype_color_class"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="is_wall",
            field=models.BooleanField(default=False),
        ),
    ]
