# Generated by Django 5.0 on 2023-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0010_building_is_wall"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TileType",
            new_name="Terrain",
        ),
        migrations.AlterModelOptions(
            name="terrain",
            options={"default_related_name": "terrains"},
        ),
        migrations.RenameField(
            model_name="tile",
            old_name="tile_type",
            new_name="terrain",
        ),
        migrations.AddField(
            model_name="building",
            name="is_city",
            field=models.BooleanField(default=False),
        ),
    ]
