# Generated by Django 5.0 on 2023-12-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0011_rename_tiletype_terrain_alter_terrain_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="allowed_terrains",
            field=models.ManyToManyField(
                to="city.terrain", verbose_name="Allowed terrains"
            ),
        ),
    ]
