# Generated by Django 5.0 on 2023-12-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0012_building_allowed_terrains"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="is_city",
        ),
        migrations.RemoveField(
            model_name="building",
            name="is_wall",
        ),
        migrations.AddField(
            model_name="building",
            name="behaviour_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Country building"),
                    (2, "City building"),
                    (3, "Type of city wall"),
                ],
                default=1,
                verbose_name="Behaviour type",
            ),
            preserve_default=False,
        ),
    ]
