# Generated by Django 5.0 on 2023-12-24 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0014_savegame_silver"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_costs",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Building costs"
            ),
        ),
    ]
