# Generated by Django 5.0 on 2023-12-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0015_building_building_costs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savegame",
            name="silver",
        ),
        migrations.AddField(
            model_name="savegame",
            name="coin",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Coin"),
        ),
    ]
