# Generated by Django 5.0 on 2023-12-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0016_remove_savegame_silver_savegame_coin"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savegame",
            name="coin",
        ),
        migrations.AddField(
            model_name="savegame",
            name="coins",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Coins"),
        ),
    ]
