# Generated by Django 5.0 on 2023-12-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0018_savegame_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="maintenance_costs",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Maintenance costs"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="taxes",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Taxes"),
        ),
    ]
