# Generated by Django 5.0 on 2023-12-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0019_building_maintenance_costs_building_taxes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="coins",
            field=models.SmallIntegerField(default=0, verbose_name="Coins"),
        ),
    ]
