# Generated by Django 5.0 on 2023-12-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0020_alter_savegame_coins"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="current_year",
            field=models.PositiveSmallIntegerField(
                default=1150, verbose_name="Current year"
            ),
        ),
    ]
