# Generated by Django 5.0 on 2023-12-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0021_savegame_current_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="behaviour_type",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Country building"),
                    (2, "Type of house"),
                    (3, "Type of city wall"),
                ],
                verbose_name="Behaviour type",
            ),
        ),
    ]
