# Generated by Django 5.0 on 2023-12-31 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0022_alter_building_behaviour_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="unrest",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Unrest"),
        ),
    ]
