# Generated by Django 5.0 on 2023-12-31 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0023_savegame_unrest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="unrest",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Unrest",
            ),
        ),
    ]
