# Generated by Django 5.0 on 2023-12-31 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0024_alter_savegame_unrest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="allowed_terrains",
        ),
        migrations.RemoveField(
            model_name="building",
            name="behaviour_type",
        ),
        migrations.CreateModel(
            name="BuildingType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "behaviour_type",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Country building"),
                            (2, "Type of house"),
                            (3, "Type of city wall"),
                        ],
                        verbose_name="Behaviour type",
                    ),
                ),
                (
                    "allowed_terrains",
                    models.ManyToManyField(
                        to="city.terrain", verbose_name="Allowed terrains"
                    ),
                ),
            ],
            options={
                "default_related_name": "building_types",
            },
        ),
        migrations.AddField(
            model_name="building",
            name="building_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="city.buildingtype",
                verbose_name="Building type",
            ),
            preserve_default=False,
        ),
    ]
