# Generated by Django 5.0 on 2023-12-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0025_remove_building_allowed_terrains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingtype",
            name="is_house",
            field=models.BooleanField(default=False, verbose_name="Is house"),
        ),
        migrations.AddField(
            model_name="buildingtype",
            name="is_wall",
            field=models.BooleanField(default=False, verbose_name="Is Wall"),
        ),
        migrations.AlterField(
            model_name="buildingtype",
            name="behaviour_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Country building"), (2, "City building")],
                verbose_name="Behaviour type",
            ),
        ),
    ]
