# Generated by Django 5.0 on 2023-12-31 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0027_building_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="housing_space",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Maintenance costs",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="building_costs",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Building costs",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="maintenance_costs",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Maintenance costs",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="taxes",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Taxes",
            ),
        ),
    ]
