# Generated by Django 5.0 on 2023-12-31 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0028_building_housing_space_alter_building_building_costs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="housing_space",
            field=models.PositiveSmallIntegerField(
                default=0,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Housing space",
            ),
        ),
    ]
