# Generated by Django 5.0 on 2023-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0029_alter_building_housing_space"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Is active"),
        ),
    ]
