# Generated by Django 5.0 on 2024-01-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0031_remove_buildingtype_behaviour_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="buildingtype",
            name="is_unique",
            field=models.BooleanField(default=False, verbose_name="Is Unique"),
        ),
    ]
