# Generated by Django 5.2.6 on 2025-10-03 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0032_buildingtype_is_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="savegame",
            name="is_enclosed",
            field=models.BooleanField(
                default=False, verbose_name="Is enclosed by wall"
            ),
        ),
    ]
