# Generated by Django 5.2.6 on 2025-10-03 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0033_savegame_is_enclosed"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrain",
            name="is_water",
            field=models.BooleanField(default=False, verbose_name="Is water"),
        ),
    ]
