# Generated by Django 5.2.6 on 2025-10-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0034_terrain_is_water"),
    ]

    operations = [
        migrations.AlterField(
            model_name="terrain",
            name="color_class",
            field=models.CharField(
                help_text="Tailwind color for usage in frontend. Example: 'bg-yellow-500'",
                max_length=20,
            ),
        ),
    ]
