# Generated by Django 5.2.6 on 2025-10-04 11:04

from django.conf import settings
from django.db import migrations


def set_default_user_for_savegames(apps, schema_editor):
    """Set all existing savegames to user_id=1."""
    Savegame = apps.get_model("city", "Savegame")
    User = apps.get_model(settings.AUTH_USER_MODEL)

    # Get or create user with id=1
    user, created = User.objects.get_or_create(
        id=1, defaults={"username": "admin", "is_staff": True, "is_superuser": True}
    )

    # Update all savegames with null user to user_id=1
    Savegame.objects.filter(user__isnull=True).update(user=user)


def reverse_migration(apps, schema_editor):
    """Reverse the migration by setting user back to null."""
    Savegame = apps.get_model("city", "Savegame")
    Savegame.objects.filter(user_id=1).update(user=None)


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0037_savegame_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(set_default_user_for_savegames, reverse_migration),
    ]
