# Generated by Django 5.2.6 on 2025-10-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0039_alter_savegame_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="coins",
            field=models.SmallIntegerField(default=1000, verbose_name="Coins"),
        ),
    ]
