# Generated by Django 5.2.3 on 2025-10-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0040_alter_savegame_coins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savegame",
            name="map_size",
            field=models.PositiveSmallIntegerField(default=20),
        ),
    ]
