# Generated by Django 5.2.3 on 2025-10-06 14:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city", "0041_alter_savegame_map_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savegame",
            name="map_size",
        ),
    ]
