# Generated by Django 5.2.3 on 2025-10-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0042_remove_savegame_map_size'),
        ('savegame', '0002_copy_savegame_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savegame',
            name='user',
        ),
        migrations.AlterField(
            model_name='tile',
            name='savegame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='savegame.savegame'),
        ),
    ]
