# Generated by Django 5.2.3 on 2025-10-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0043_remove_savegame_user_alter_tile_savegame'),
        ('edict', '0002_alter_edictlog_savegame'),
        ('milestone', '0003_alter_milestonelog_savegame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Savegame',
        ),
    ]
