# Generated by Django 5.2.7 on 2025-10-26 06:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0044_delete_savegame'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='demolition_costs',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Demolition costs'),
        ),
    ]
