# Generated by Django 5.2.7 on 2025-10-25 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0044_populate_coat_of_arms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savegame',
            name='coat_of_arms',
            field=models.ImageField(upload_to='coat_of_arms/', verbose_name='Coat of Arms'),
        ),
    ]
