# Generated by Django 5.2.7 on 2025-10-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0045_add_demolition_costs'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtype',
            name='type',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Ruins')], default=1, verbose_name='Type'),
        ),
    ]
