# Generated by Django 5.2.7 on 2025-10-26 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0046_add_building_type_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='defense_value',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Defense value'),
        ),
    ]
