# Generated by Django 5.2.7 on 2025-10-28 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0047_building_defense_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='prestige',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prestige'),
        ),
    ]
