# Generated by Django 5.2.7 on 2025-10-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0048_building_prestige'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terrain',
            name='color_class',
        ),
        migrations.AddField(
            model_name='terrain',
            name='image_filename',
            field=models.CharField(default='default.png', help_text="Filename of the terrain image in static/img/tiles/. Example: 'grass.png'", max_length=100),
        ),
    ]
