# Generated by Django 5.2.7 on 2025-10-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0049_remove_terrain_color_class_terrain_image_filename'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS thread_activethread;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS thread_threadtype;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
