# Generated by Django 5.2.7 on 2026-03-15 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0049_remove_terrain_color_class_terrain_image_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='wall_hitpoints',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
